# Generated by Django 2.2.24 on 2025-07-24 11:44
from django.db import migrations
from phonenumbers import is_valid_number, parse, is_possible_number, NumberParseException


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    updates_flats = []
    for flat in Flat.objects.iterator():
        flat.owner_pure_phone = get_pure_phone_number(flat.owners_phonenumber)
        updates_flats.append(flat)
    Flat.objects.bulk_update(updates_flats, ["owner_pure_phone"])


def get_pure_phone_number(phone_number):

    if not phone_number:
        return None
    try:
        parsed_phone_number = parse(phone_number, 'RU')
    except NumberParseException:
        return None

    if not is_possible_number(parsed_phone_number) or not is_valid_number(parsed_phone_number):
        return None
    return parsed_phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
