# Generated by Django 2.2.24 on 2025-08-04 08:47

from django.db import migrations


def update_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    for flat in Flat.objects.iterator():
        if flat.owner:
            obj, created = Owner.objects.get_or_create(name=flat.owner, defaults={
                "phone": flat.owners_phonenumber,
                "pure_phone": flat.owner_pure_phone

            })
            obj.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(update_owner, reverse_code=migrations.RunPython.noop),
    ]
