# Generated by Django 2.2.24 on 2025-08-08 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250804_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='like_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
