# Generated by Django 2.2.24 on 2025-08-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20250808_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaint',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamets', to='property.Flat', verbose_name='На какую квартиру жаловались'),
        ),
    ]
