# Generated by Django 2.2.24 on 2025-08-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250808_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет'), (None, 'Неизвестно')], db_index=True, default=None, null=True, verbose_name='Новостройка'),
        ),
    ]
